#!/usr/bin/env bash
set -ex

mkdir build
pushd build

cmake -G Ninja \
      -DCMAKE_BUILD_TYPE=Release \
      ../src

cmake --build .

./hpxct \
    /data/ctBones.vti \
   	| tee /results/output

ls
cp output_0.vti /results/
cp output.vtp /results/

popd

