#!/usr/bin/env bash
set -e # abort on error
set -x # verbose output

# -- Teem

export TEEM_VERSION="1.11.0"

mkdir teem-source

curl -L https://netcologne.dl.sourceforge.net/project/teem/teem/1.11.0/teem-1.11.0-src.tar.gz | tar zx -C teem-source --strip-components 1

mkdir teem-build
pushd teem-build

cmake -G Ninja \
      -D CMAKE_INSTALL_PREFIX=/usr \
      ../teem-source

cmake --build . --target install

popd

# rm -rf teem-source teem-build

# --- HPX

export HPX_VERSION="1.4.1"

mkdir hpx-source

curl -L https://github.com/STEllAR-GROUP/hpx/archive/${HPX_VERSION}.tar.gz | tar zx -C hpx-source --strip-components 1

mkdir hpx-build
pushd hpx-build

cmake -G Ninja \
      -D CMAKE_INSTALL_PREFIX=/usr \
      -D CMAKE_BUILD_TYPE=Release \
      -D HPX_WITH_MALLOC=tcmalloc \
      -D HPX_WITH_EXAMPLES=OFF \
      -D HPX_WITH_TESTS=OFF \
      -D HPX_WITH_PAPI=ON \
      ../hpx-source

cmake --build . --target install

popd

rm -rf hpx-source hpx-build
